# Doc: https://homebrew-file.readthedocs.io/en/latest/usage.html
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "nrlquaker/createzap"
tap "railwaycat/emacsmacport"
tap "versent/homebrew-taps"
cask_args appdir: "/Applications", require_sha: true

# ===brew===
brew "bash"
brew "bat"
brew "bazel"
brew "buildifier"
brew "ccls"
brew "clang-format"
brew "cmake"
brew "curl"
brew "dust" # replacement of du
brew "emacs-mac", args: ["with-modules"]
brew "exa" # replacement of ls
brew "fd" # replacement of find
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "gh"
brew "ghc"
brew "ghq"
brew "gibo"
brew "git"
brew "git-delta"
brew "gitui"
brew "gnu-sed"
brew "go"
brew "golangci-lint"
brew "grep"
brew "haskell-stack"
brew "hyperfine" # for benchmark
brew "jq" # json processor
brew "llvm"
brew "make"
brew "mas"
brew "mysql"
brew "neofetch"
brew "neovim"
brew "node"
brew "nvm"
brew "openssl"
brew "pandoc"
brew "pkg-config"
brew "procs" # replacement of ps
brew "pyenv"
brew "python@3.9"
brew "ripgrep" # replacement of grep
brew "rlwrap"
brew "roswell"
brew "sbcl"
brew "sd" # replacement of sed
brew "shellcheck"
brew "starship"
brew "svn"
brew "tealdeer"
brew "tectonic"
brew "tmux"
brew "tokei"
brew "unzip"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"

# ===cask===
cask "alacritty"
cask "alfred"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "google-japanese-ime"
cask "hhkb-pro-driver"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "keycastr"
cask "mactex-no-gui"
cask "microsoft-edge"
cask "obs"
cask "shiftit"
cask "slack"
cask "spotify"
cask "typora"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

# ===mas===
mas "xcode", id: 497799835
