# Doc: https://homebrew-file.readthedocs.io/en/latest/usage.html
tap "discoteq/discoteq"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "nrlquaker/createzap"
tap "versent/homebrew-taps"
tap "alexhallam/tidy-viewer"
cask_args appdir: "/Applications"

# ===brew===
brew "clang-format"
brew "icarus-verilog"
brew "java"
brew "jenv"
brew "make"
brew "nvm"
brew "openjdk@11"
brew "openjdk@8"
brew "pyenv"
brew "reattach-to-user-namespace"
brew "telnet"
brew "vcpkg"
# ===GNU===
brew "findutils"

# ===cask===
cask "alfred"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "hhkb-pro-driver"
cask "karabiner-elements"
cask "keybase"
cask "keycastr"
cask "mactex-no-gui"
cask "microsoft-edge"
cask "obs"
cask "openaudible"
cask "shiftit"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
cask "zulip"

