# Doc: https://homebrew-file.readthedocs.io/en/latest/usage.html
tap "discoteq/discoteq"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "nrlquaker/createzap"
tap "versent/homebrew-taps"
tap "alexhallam/tidy-viewer"
cask_args appdir: "/Applications"

# ===brew===
brew "nvm"
brew "pyenv"
brew "reattach-to-user-namespace"
brew "telnet"
brew "vcpkg"

# ===cask===
cask "alacritty"
cask "amethyst"
cask "brave-browser"
cask "deepl"
cask "gitify"
cask "gtkwave"
cask "intellij-idea-ce"
cask "notion"
cask "alfred"
cask "discord"
cask "docker"
cask "dropbox"
cask "freedom"
cask "firefox"
cask "gitify"
cask "google-chrome"
cask "google-japanese-ime"
cask "hhkb-pro-driver"
cask "karabiner-elements"
cask "keybase"
cask "keycastr"
cask "microsoft-edge"
cask "obs"
cask "openaudible"
cask "shiftit"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
cask "zulip"

